name: CI/CD
on: [push, workflow_dispatch]
jobs:
  buildOnLinuxPlatform:
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: WebGL
            channel: html
            package: build/WebGL/WebGL
          - targetPlatform: StandaloneLinux64
            channel: linux
            package: build/StandaloneLinux64
    name: Build (WebGL) for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - name: Cache unity library folder
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform}}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform}}-
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload full build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: FullBuild-${{ matrix.targetPlatform }}
          path: build

      # Upload to itch.io page
      - name: Uploads to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.channel }}
          ITCH_GAME: test-mattia-non-toccare
          ITCH_USER: lopossum-sognante
          PACKAGE: ${{ matrix.package }}